---
    - name: Create VPC "{{ vpc_name }}" with subnet "{{ vpc_cidr }}" in region "{{ region }}"
      ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpc_cidr }}"
        region: "{{ region }}"
        state: present
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: freebsd_vpc

    - name: Create subnet "{{ public_subnet_cidr }}" in VPC "{{ vpc_name }} ("{{ vpc.vpc.id }}")
      ec2_vpc_subnet:
       state: present
       vpc_id: "{{ freebsd_vpc.vpc.id }}"
       region: "{{ region }}"
       cidr: "{{ public_subnet_cidr }}"
       aws_access_key: "{{ aws_access_key }}"
       aws_secret_key: "{{ aws_secret_key }}"
       map_public: yes
       resource_tags:
         Name: "{{ public_subnet_name }}"
      register: freebsd_public_subnet

    - name: Create IGW "{{ igw_name }}" on VPC "{{ vpc_name }} ("{{ vpc.vpc.id }}")
      ec2_vpc_igw:
       vpc_id: "{{ freebsd_vpc.vpc.id }}"
       region: "{{ region }}"
       aws_access_key: "{{ aws_access_key }}"
       aws_secret_key: "{{ aws_secret_key }}"
       state: "present"
       tags:
         Name: "{{ igw_name }}"
      register: freebsd_igw

    - name:               Set up public subnet route table
      ec2_vpc_route_table:
        vpc_id:           "{{ freebsd_vpc.vpc.id }}"
        region:           "{{ region }}"
        aws_access_key:   "{{ aws_access_key }}"
        aws_secret_key:   "{{ aws_secret_key }}"
        tags:
          Name:           "Public"
        subnets:
          - "{{ freebsd_public_subnet.subnet.id }}"
        routes:
          - dest:         "0.0.0.0/0"
            gateway_id:   "{{ freebsd_igw.gateway_id }}"

    - name: Create security group "{{ security_group_name }}" on VPC "{{ vpc_name }} ("{{ vpc.vpc.id }}")
      ec2_group:
        name: "{{ security_group_name }}"
        description: The security group
        region: "{{ region }}"
        vpc_id: "{{ freebsd_vpc.vpc.id }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
      register: freebsd_security_group 

    - name: Create EC2 Instance of type "{{ instance_type }}" with ami "{{ image }}" in VPC "{{ vpc_name }} ("{{ vpc.vpc.id }}")
      ec2:
        image: "{{ image }}"
        wait: true 
        instance_type: "{{ instance_type }}"
        region: "{{ region }}"
        groups: "{{ security_group_name}}"
        vpc_subnet_id: "{{ freebsd_public_subnet.subnet.id }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        count: "{{ count }}"
      register: ec2

